/**
 * Skills Index
 * Auto-generated by Self-Evolution System
 */

module.exports.TestApprovedSkill = require('./test-approved-skill/scripts/test-approved-skill').TestApprovedSkill;
module.exports.ApprovalTestSkill = require('./approval-test-skill/scripts/approval-test-skill').ApprovalTestSkill;
